### ISSUE TITLE
Discuss libunity

### ISSUE THREAD

**Issue by memnoth** [flathub/com.github.calo001.fondo#1]
I really wonder libunity is seriously necessary and what it is exactly doing on fondo.
There might be somewhere(linux distros) to require this, but in flatpak too...?

What do you think about it? @calo001 @bilelmoussaoui

**Comment by calo001** [comment]
@memnoth I use libunity because elementary OS (my main distro target) needs it in Plank to show the download progress :+1: 

![libunity2](https://user-images.githubusercontent.com/9545757/52166474-74bcdc80-26d3-11e9-996d-50d688783b84.png)

**Comment by bilelmoussaoui** [comment]
I will take a look at that after FOSDEM.

**Comment by mjog** [comment]
Had a request for this for Geary (https://github.com/flathub/org.gnome.Geary/issues/13), and there is one for Thunderbird (https://github.com/flathub/org.mozilla.Thunderbird/issues/10), too.

It probably needs some talk perms, since the API works by sending updates via signals on the com.canonical.Unity.LauncherEntry dbus interface.

**Comment by memnoth** [comment]
https://github.com/flathub/org.gnome.Geary/pull/14

We could refer to the PR, good works @mjog !

**Comment by bilelmoussaoui** [comment]
I think it's better to include libunity on elementary Juno baseApp as it's part of the elementary ecosystem. It's widely used by elementary apps.

**Comment by mjog** [comment]
Also widely used in the Ubuntu ecosystem, too.

**Comment by memnoth** [comment]
@bilelmoussaoui It's a good idea.
